### ISSUE TITLE
Add docs about `deps.yaml` format of block

### ISSUE THREAD

**Issue by blond** [enb-bem/enb-bem-techs#18]

**Comment by Immuzov** [comment]
@blond, искал искал, не нашел. Не получается это в yaml перевести, подскажете?
```js
({
  shouldDeps: [
    { block: 'controller' },
  ],
});
```

**Comment by tadatuta** [comment]
В `deps.yaml` зависимости по умолчанию воспринимаются как `shouldDeps`, а для `mustDeps` необходимо добавить поле `required: true`:
```yaml
- block: i-bem
  required: true
  elem: [html, i18n]
- mods: { lang: [en, ru] }
```
